### ISSUE TITLE
 FAIL tests/tissueExpression.test.js: Cannot find module 'es6-promise' from 'promise.js'

### ISSUE THREAD

**Issue by johasalinas** [intermine/bluegenes-tissue-expression-visualizer#10]
I'm having this issues when I run the tests in bluegenes-tissue-expression-visualizer:

 FAIL  tests/tissueExpression.test.js : 
**Cannot find module 'es6-promise' from 'promise.js'**

 However, Jest was able to find:
    	'./promise.js'

<img width="1196" alt="Screen Shot 2020-03-14 at 9 48 39 PM" src="https://user-images.githubusercontent.com/5965987/76738004-1c775b80-676a-11ea-961a-e4730338d5ca.png">

**Comment by heralden** [comment]
Could you try adding `es6-promise` as a dependency? I think the error happens because it's listed as a devDependency in imjs (used by this visualization) instead of a regular dependency.

**Comment by johasalinas** [comment]
After install the following required dependencies:
    "JSONStream": "^1.3.5",
    "es6-promise": "^4.2.8"

Four tests are still failling, looks like is realated with https://github.com/intermine/imjs/issues/65 and https://github.com/intermine/imjs/issues/63.

**Comment by akshatbhargava123** [comment]
@uosl as @jsnunki suggested, I also believe the tests are broken due to imjs not running on node environment.

@jsnunki what node version are you trying with, could you share more details here.

**Comment by jsnunki** [comment]
Hi @akshatbhargava123 
I tried versions 6, 8, 10 and 12. But the tests still work.

**Comment by johasalinas** [comment]
Hi @akshatbhargava123, @uosl 
I tried versions 6, 8, 10 and 12. But the tests but still not work and now I have this:

<img width="732" alt="Screen Shot 2020-03-18 at 7 26 09 PM" src="https://user-images.githubusercontent.com/5965987/76994287-6f116d00-694e-11ea-8883-54d99d713544.png">
<img width="709" alt="Screen Shot 2020-03-18 at 7 26 26 PM" src="https://user-images.githubusercontent.com/5965987/76994293-7173c700-694e-11ea-9cce-c2606dc298f4.png">
<img width="731" alt="Screen Shot 2020-03-18 at 7 26 41 PM" src="https://user-images.githubusercontent.com/5965987/76994297-72a4f400-694e-11ea-9ff1-6d949a1496a1.png">

After changing the URL from https to http I'm getting these errors:
<img width="989" alt="Screen Shot 2020-03-18 at 7 33 00 PM" src="https://user-images.githubusercontent.com/5965987/76994945-65d4d000-694f-11ea-8809-34feca7a5f73.png">
<img width="974" alt="Screen Shot 2020-03-18 at 7 32 41 PM" src="https://user-images.githubusercontent.com/5965987/76994955-68cfc080-694f-11ea-802a-a1ac9fe3d637.png">
<img width="928" alt="Screen Shot 2020-03-18 at 7 32 36 PM" src="https://user-images.githubusercontent.com/5965987/76994959-69685700-694f-11ea-9ffc-2df225f965e9.png">

**Comment by heralden** [comment]
I fixed the issue in imjs with https://github.com/intermine/imjs/pull/68, updated imjs and the tests are passing now.
