### ISSUE TITLE
package.json does not contain server script

### ISSUE THREAD

**Issue by jshreyans** [intermine/bluegenes-tissue-expression-visualizer#12]
[This](https://github.com/intermine/bluegenes-tissue-expression-visualizer/blob/master/README.md#developing) section of the README file says that the project can be served at `localhost:3456` via the `npm run server` script, but the script itself is missing from the [package.json](https://github.com/intermine/bluegenes-tissue-expression-visualizer/blob/master/package.json) file. 
In keeping with the structure of the other visualization tools, we can remove the instruction from the README altogether and just use `npm run dev`

**Comment by johasalinas** [comment]
@uosl You could assign it to me and I can correct it.

**Comment by johasalinas** [comment]
@uosl @jshreyans  I opened a PR https://github.com/intermine/bluegenes-tissue-expression-visualizer/pull/13

**Comment by johasalinas** [comment]
Improvement of the text of the README.md  is Done! ✅@uosl @jshreyans
