### ISSUE TITLE
Make React components usable if installed via NPM

### ISSUE THREAD

**Issue by akshatbhargava123** [intermine/bluegenes-tissue-expression-visualizer#14]
Currently, the react components are not usable if we install the npm package for the tool. This is because JSX is compiled (only under `src`) using webpack during the `build` process which is fine so we need to export the "built" react component from our package.

It probably requires to re-configure some webpack configuration. [This](https://jasonwatmore.com/post/2018/04/14/react-npm-how-to-publish-a-react-component-to-npm) might be a useful link.

**Comment by heralden** [comment]
Closing as we decided to abandon this approach.
