### ISSUE TITLE
npm install failure under Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by sammyjava** [intermine/bluegenes-tissue-expression-visualizer#16]
I get the following under Ubuntu 20.04.1 LTS using npm 7.0.8 (manually installed). Suggestions?
```
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/@babel%2fplugin-transform-modules-commonjs reason: Unexpected end of JSON input
```

**Comment by sammyjava** [comment]
BTW I was able to get around it by downloading the installed files from another server (Fedora 33) but I wonder what could be done to make this install from scratch on this Ubuntu box.

**Comment by heralden** [comment]
I can't reproduce this on node v15.2.1 and npm v7.0.8 (Void 5.8.16_1).

I wonder if this was a temporary hiccup at https://registry.npmjs.org/. Could you do another clone of this repo on the Ubuntu system and see if it happens again?

**Comment by sammyjava** [comment]
I can't seem to cure it. I downloaded the pre-rolled binary of node v15.2.0 and had the same result. So then I compiled v15.2.1 from the tarball and still had the same result. It's something funky with Ubuntu 20, I fear. In any case, not your problem so I'll close this.
```
shokin@morangie:~/bluegenes-tissue-expression-visualizer$ npm -v
7.0.8
shokin@morangie:~/bluegenes-tissue-expression-visualizer$ node -v
v15.2.1
shokin@morangie:~/bluegenes-tissue-expression-visualizer$ npm install
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/@babel%2fplugin-transform-modules-commonjs reason: Unexpected end of JSON input
```
And now I see that it's been reported on StackOverflow, so it's a "known" bug, at least. https://stackoverflow.com/questions/64625539/npm-err-invalid-json-response-body-at-http-registry-npmjs-org-ansi-escapes-re

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shokin/.npm/_logs/2020-11-16T19_31_31_031Z-debug.log
```

**Comment by sammyjava** [comment]
Oh, weird. `npm cache clean --force` fixed it! I must have had some cruft in my npm cache. Good to know!
