### ISSUE TITLE
[easy task] add preview.png to root of this repo

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes-tissue-expression-visualizer#5]
If you would like to pick this issue up, please comment on the issue to let us know you're working on it :) 

## Task: 
Add preview.png to the root of this repository

## How to do this

1. Go to the repo README, and follow instructions to clone and install this repository.
2. Run `npm run dev` and visit http://localhost:3456
3. Capture a screenshot of the application in action! Try to avoid extra/un-needed whitespace, and try to make it square-ish (this doesn't have to be exact).  
4. Save it in the root of this repo, commit it, and make a PR :tada: 

Context: these previews will be used here: http://bluegenes.apps.intermine.org/default/debug/tool-store - you can look for other repos under intermine to find similar tasks for other bluegenes-* repositories as several tools are missing previews.

 
### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by rajkharvar** [comment]
I am working on this issue

**Comment by rajkharvar** [comment]
I am getting **No associated organism found!** Can you elaborate on what should be the expected output? If it is the same Please let me know to make PR for it.

**Comment by yochannah** [comment]
Whoops - thanks for taking a look at this! 😊 I'll have to check what's up
tomorrow and let you know.

**Comment by heralden** [comment]
Very sorry about this, @rajkharvar. Seems like this issue got lost in the heap.
The error was on our side; the gene ID in `demo.html` didn't return any tissue expression data.
